version: "3"

services:
  webserver:
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    networks:
      - alligator-network
    ports:
      - 80:80
      - 443:443
    links:
      - swarm:swarm
      - videostream:videostream
    depends_on:
      - swarm
      - videostream
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/data/certbot/conf:/etc/letsencrypt
      - ./nginx/data/certbot/www:/var/www/certbot

  swarm:
    build: ./telemetary
    restart: unless-stopped
    tty: true
    depends_on:
      - db
    volumes:
      - ./telemetary:/bin
    networks:
      - alligator-network
    ports:
      - "8080:8080"

  videostream:
    build: ./videostream
    restart: unless-stopped
    tty: true
    networks:
      - alligator-network
    volumes:
      - ./videostream:/videostream
      # - ./certs:/opt/certs
    ports:
      - 1935:1935
      - 8081:80

  db:
    image: postgres:9.6-alpine
    env_file:
      - .env
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
    ports:
      - "4432:5432"
    restart: unless-stopped
    tty: true
    networks:
      - alligator-network

volumes:
  pgdata: {}

networks:
  alligator-network:
    driver: bridge
